version: '2'
services:
  docker-redis:
    image: alannesta/redis:0.2.0  # 0.2.0 persist local file
    ports:
        - "6379:6379"
    restart: unless-stopped

  docker-crawler:
    image: alannesta/crawler-service:0.1.3
    restart: unless-stopped
    depends_on:
        - docker-redis
    environment:
        REDIS_URL: //docker-redis:6379
        NODE_ENV: docker
